### ISSUE TITLE
Please help me, i can not get the rx6600M working on my new FN60G

### ISSUE THREAD

**Issue by tungd-0380** [jhihhe/FEVM-FN60G-Hackintosh#1]
Hello i just bought a brand new FN60G with 6600M for hackintosh,
but when i started it up, the opencore GUI is so low resolution, and when it boots into macOS, there's only maximum 1080p choice (my monitor is 4k resolution),
the GPU only shows : Radeon Navi 23 8GB
![image](https://github.com/jhihhe/FEVM-FN60G-Hackintosh/assets/49553331/b10ca035-fe58-4382-b5a1-408d9becea00)
![image](https://github.com/jhihhe/FEVM-FN60G-Hackintosh/assets/49553331/528d4d1b-44e1-4a5b-86f5-8a5c051dc77d)
How did you get your GPU fully metal qe/ci ? please help me

**Comment by tungd-0380** [comment]
i just figured out the Vbios of RX6600M is the problem, can you help me to extract and send me that, thanks a lot

**Comment by jhihhe** [comment]
![2466748902](https://github.com/jhihhe/FEVM-FN60G-Hackintosh/assets/79625790/e8adeb02-f029-4ce3-9c92-224d4f431edc)

**Comment by jhihhe** [comment]
> i just figured out the Vbios of RX6600M is the problem, can you help me to extract and send me that, thanks a lot

![2466748902](https://github.com/jhihhe/FEVM-FN60G-Hackintosh/assets/79625790/03832abd-3e67-480f-afaa-b14e6613c767)

**Comment by jhihhe** [comment]
> Hello i just bought a brand new FN60G with 6600M for hackintosh, but when i started it up, the opencore GUI is so low resolution, and when it boots into macOS, there's only maximum 1080p choice (my monitor is 4k resolution), the GPU only shows : Radeon Navi 23 8GB ![image](https://private-user-images.githubusercontent.com/49553331/307563051-b10ca035-fe58-4382-b5a1-408d9becea00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjQ4MTcsIm5iZiI6MTcwOTAyNDUxNywicGF0aCI6Ii80OTU1MzMzMS8zMDc1NjMwNTEtYjEwY2EwMzUtZmU1OC00MzgyLWI1YTEtNDA4ZDliZWNlYTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZmQ4MWI5YTU1MGIwMzMyNmE1NzQ5ZTM3NWViYTM3NzBiMWE1NDAzMTk2N2E1ZDM0MDdmY2YzOTQ4ZWFmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRw9Rlc2AJb6Jzmx9WU3biGrBcABGtupegpnnODOxUQ) ![image](https://private-user-images.githubusercontent.com/49553331/307563058-528d4d1b-44e1-4a5b-86f5-8a5c051dc77d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjQ4MTcsIm5iZiI6MTcwOTAyNDUxNywicGF0aCI6Ii80OTU1MzMzMS8zMDc1NjMwNTgtNTI4ZDRkMWItNDRlMS00YTViLTg2ZjUtOGE1YzA1MWRjNzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjdmMWVjOGRkZmU1YzNmNjliMzBmODQwOThkYTcwYTYxMDFhZDRhZDE4ZjRmNGU4NzFjNDM0NGVhNTM1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwzDbqulluxwFOzoEDbY_jQgB0_PrICk2uVcmlg8bvs) How did you get your GPU fully metal qe/ci ? please help me

Three solutions:
1. Use cables with hdmi 2.1 or dp 1.4 specifications
2. Open hidpi "bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh)"
"
3. Use BetterDisplay Pro app to create a virtual display to mirror HiDPi resolution

**Comment by tungd-0380** [comment]
thank you my monitor gone bad with DP cable, i tried HDMI cable and everything is fine now @jhihhe

**Comment by jhihhe** [comment]
> thank you my monitor gone bad with DP cable, i tried HDMI cable and everything is fine now @jhihhe

💯
