### ISSUE TITLE
睡眠唤醒

### ISSUE THREAD

**Issue by hhanworth** [jhihhe/FEVM-FN60G-Hackintosh#2]
您好，大佬。我的fn60g使用您的efi，睡眠后，开始正常但是过一阵子，电源指示灯开始常亮，风扇开始转，屏幕也开始显示开启但是没有输出画面，过一会自动又正常睡眠。
导致屏幕过一阵子会自动亮一会，虽然没有画面，感觉这样久了会烧屏幕。这个有解吗。

**Comment by hanhan-stupid** [comment]
![Uploading 截屏2024-03-28 21.55.26.png…]()

**Comment by jhihhe** [comment]
![27421711799503_ pic](https://github.com/jhihhe/FEVM-FN60G-Hackintosh/assets/79625790/21f4f7e1-4864-4f21-88b3-0489012aa908)

**Comment by jhihhe** [comment]
> 您好，大佬。我的fn60g使用您的efi，睡眠后，开始正常但是过一阵子，电源指示灯开始常亮，风扇开始转，屏幕也开始显示开启但是没有输出画面，过一会自动又正常睡眠。 导致屏幕过一阵子会自动亮一会，虽然没有画面，感觉这样久了会烧屏幕。这个有解吗。
![27421711799503_ pic](https://github.com/jhihhe/FEVM-FN60G-Hackintosh/assets/79625790/76da72c7-ab8c-4fea-af74-4201b7cf40ea)

**Comment by ZackYJz** [comment]
@jhihhe 大佬，现在睡眠还是会秒醒，已经关闭了这个电能小憩

**Comment by jhihhe** [comment]
> @jhihhe 大佬，现在睡眠还是会秒醒，已经关闭了这个电能小憩

EFI睡眠测试没问题,是其他原因,建议上远景看看

**Comment by ZackYJz** [comment]
> > @jhihhe 大佬，现在睡眠还是会秒醒，已经关闭了这个电能小憩
> 
> EFI睡眠测试没问题,是其他原因,建议上远景看看

请您的机器是V1还是V2呢
