### ISSUE TITLE
help with 13900T (ES) bios compatibility

### ISSUE THREAD

**Issue by tungd-0380** [jhihhe/FEVM-FN60G-Hackintosh#3]
Hello jhihhe, i just bought a 13900T(ES) with cpu code `Q0PV` but the FN60G is not accepting it, i was running an i5 13500 and it was running perfectly

can you modify the new bios and add some of ES CPU code into it?
really appreciate, thanks!

**Comment by jhihhe** [comment]
> Hello jhihhe, i just bought a 13900T(ES) with cpu code `Q0PV` but the FN60G is not accepting it, i was running an i5 13500 and it was running perfectly
> 
> can you modify the new bios and add some of ES CPU code into it? really appreciate, thanks!

The manufacturer does not currently support the ES version CPU.
Please wait for official support. However, there is a high probability that the ES version will not be supported in the future. The recommended CPU for this machine, is up to 13600T.
