### ISSUE TITLE
前置type-c口无法使用

### ISSUE THREAD

**Issue by hhanworth** [jhihhe/FEVM-FN60G-Hackintosh#4]
前置type-c口无法使用，大家都这样还是只有我这样，可以修复吗

**Comment by jhihhe** [comment]
> 前置type-c口无法使用，大家都这样还是只有我这样，可以修复吗

升级bios,更换线缆,储存设备应该是支持的,现在支持不太全,热插拔也不太好,建议开机前就插上,另外apple牌手机没办法用typec连接

**Comment by hhanworth** [comment]
使用最新的efi发现iPhone可以连接前置typec口了，但是升级sequoia，无法使用iPhone镜像，能解决吗

**Comment by jhihhe** [comment]
> 使用最新的efi发现iPhone可以连接前置typec口了，但是升级sequoia，无法使用iPhone镜像，能解决吗

黑苹果没有T2芯片，暂时不可能实现使用iPhone镜像功能

**Comment by ZackYJz** [comment]
> 使用最新的efi发现iPhone可以连接前置typec口了，但是升级sequoia，无法使用iPhone镜像，能解决吗

你好，请问你的是V2版本吗？使用新EFI后睡眠唤醒和前置typec口都正常了吗
